version: '3.8'
services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports: 
      - 27017:27017
    volumes:
      - ./db/:/data/db
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/raabitmq/log/:/var/log/rabbitmq
    networks:
      - mynet

  
  backend:
    restart: always
    build: 
      context: ./
    volumes:
      - .:/src 
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      PORT: 4000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      MONGO_URL: mongodb://mongodb:27017/sysmap_api
      JWT_SECRET: "accesstoken"
    ports:
      - 4000:4000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
